if submit:
    payload = {
        "Time": Time,
        "Amount": Amount,
        **features
    }

    try:
        response = requests.post(API_URL, json=payload)
        result = response.json()

        st.subheader("🔍 Prediction Result")

        risk = result["risk_level"]
        prob = result["fraud_probability"]

        if risk == "HIGH RISK":
            st.error(f"🚨 HIGH RISK TRANSACTION\n\nFraud Probability: {prob}")
        elif risk == "MEDIUM RISK":
            st.warning(f"⚠️ MEDIUM RISK TRANSACTION\n\nFraud Probability: {prob}")
        else:
            st.success(f"✅ LOW RISK TRANSACTION\n\nFraud Probability: {prob}")

        st.caption(
            "This prediction is generated by a deployed FastAPI backend. "
            "Thresholds are configurable based on business cost trade-offs."
        )

    except Exception as e:
        st.error("API call failed")
        st.write(e)
